### PR TITLE
add a method returning the underlying Repo object from a Repository

### PR DESCRIPTION
**Pull request by euclio**

### CODE REVIEW

**Comment by euclio** [comment]
Rebased.

**Comment by euclio** [comment]
Rebased.

**Comment by euclio** [comment]
Rebased. @softprops, is this something you're interested in having? Does the API need to be changed?

**Comment by softprops** [comment]
merged. sry it took so long, I've been making lots of changes recently.

**Comment by softprops** [comment]
your changes are now published in version `0.3.9`

**Pull request merged**
