### PR TITLE
Implement organization repository list support

### PR DESCRIPTION
**Pull request by carols10cents**
Hi! I added support for organization repository listing, in a similar way to how you did user repo listing. I'm more than happy to make any changes you'd like :heart:

### CODE REVIEW

**Comment by softprops** [comment]
Very nice. Thank you. I'm aiming to publish a release this weekend for all the new serde stuff. This will make a nice addition :)

**Comment by softprops** [comment]
Looks like travis didn't like that and the reason was [ambiguous](https://travis-ci.org/softprops/hubcaps/jobs/117053873#L349). I'll try to sort that out.

**Comment by softprops** [comment]
I think it may have to do with serde_codgen [v0.7.1](https://crates.io/crates/serde_codegen/0.7.1) ( the latest ) 0.7 release which as an upgraded dependency on syntex v0.30 ( from v0.29) while my cargo build specifies build dependencies on serde_codgen v0.7 and syntex v0.29.  My guess is that cargo is pulling 0.7.1 and using syntex 0.29 which may, in someway cause this error.

**Comment by softprops** [comment]
@carols10cents  can you try merging master and doing one more push to your branch. That should retrigger travis's test run against the different versions of rust again. I updated the my build dependency on syntex which I think should solve the problem

**Comment by carols10cents** [comment]
Will do!!

**Comment by carols10cents** [comment]
Looks like that worked!!

**Comment by carols10cents** [comment]
I just added one more commit changing the doc comment i added-- I reread it and noticed it didn't make any sense, haha :) I fixed a few other little typos while I was in there too :heart:

**Comment by softprops** [comment]
[published](https://crates.io/crates/hubcaps/)

**Pull request merged**
