### PR TITLE
Add `/user` endpoint support

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Comment by dpc** [comment]
Just hacked this together. I need to actually test in my app, but feel free to point out any wrongdoings already. :)

**Comment by softprops** [comment]
Well that was fast!

**Comment by softprops** [comment]
I'll publish a new release tomorrow. Thanks for the pull @dpc!

**Comment by dpc** [comment]
I don't know why but it's not working for me right now. I've replaced my `reqwest` code doing it with this one, and I'm geting: `invalid type: null, expected a string at line 1 column 852! `. Investigating.

**Comment by softprops** [comment]
That typically means one of the String fields needs to be of Option <String> type

**Comment by dpc** [comment]
Oh. It's `hireable`. I don't even know what is it's actual type, since it's "null" for me.

**Comment by softprops** [comment]
published a new version with your changes https://crates.io/crates/hubcaps and added some [examples](https://github.com/softprops/hubcaps/blob/master/examples/users.rs#L22-L32)

**Comment by dpc** [comment]
Thanks!

**Pull request merged**
