### PR TITLE
Anonymous Gists do not have an owner

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by dwijnand** [comment]
ironically.. https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/

**Comment by shepmaster** [comment]
> ironically

Not really ironic. *Because* of that, I was switching the Rust Playground to use authenticated gists, which means that it's done server-side, which means that it's now using hubcaps. 

That being said, *every single Playground gist* before this is still anonymous and those will continue to exist "forever". Thus, the Playground has to be able to load them. That's why I'm using this branch in production.

**Comment by dwijnand** [comment]
I suspected the timing wasn't so accidental.

it just tickled me: finally adding support for anonymous gists.. that are being deprecated :)

**Comment by softprops** [comment]
Sry about about not following on this sooner. What do we want to do with this pull now?

**Comment by shepmaster** [comment]
> What do we want to do with this pull now?

As I mentioned, the API continues to return gists without owners because anonymous gists are still readable. The only change is that GitHub will no longer allow *creating* them.

**Comment by softprops** [comment]
done. there's one more thing I'd like to do for https://github.com/softprops/hubcaps/issues/113 before pushing a release. But I may have to wait on https://github.com/softprops/hubcaps/issues/112#issuecomment-375942067 before I can do that. Once the futures-rs push is out I can wrap this up in a new release

**Comment by softprops** [comment]
@shepmaster this is now published in 0.4.5

**Comment by shepmaster** [comment]
Thank you!

**Comment by softprops** [comment]
Thanks for the patch. Sry for the delay. I was waiting on the futures rs thing.

**Pull request merged**
